import { useEffect, useState } from "react";
import { TableGrid } from "../../../components/TableGrid";
import { ToolbarContainer } from "../../../components/ToolbarContainer";
import { ScheduleProps } from "./interfaces";
import { columns } from "./table/columns";
import { CreateModal } from "./models/createModal";

export function Schedule() {
  const [rows, setRows] = useState<ScheduleProps[]>([]);

  const responseData = [
    {
      id: "1",
      data: "20/10/2022",
      Hora: "02:00pm",
      RG: "151638366",
      Nome: "Eduardo Pinheiro",
      Empresa: "Instituto CTS",
      Setor: "Departamento de P&D",
      visitado: "Alessandra Rocha",
      Refeição: "Sim",
      Pagamento: "Por conta própria",
      idShedule: "248503950599",
    },
    {
      id: "2",
      data: "20/10/2022",
      Hora: "02:00pm",
      RG: "151638366",
      Nome: "Eduardo Pinheiro",
      Empresa: "Instituto CTS",
      Setor: "Departamento de P&D",
      visitado: "Alessandra Rocha",
      Refeição: "Sim",
      Pagamento: "Por conta própria",
      idShedule: "399651231231",
    },
    {
      id: "3",
      data: "20/10/2022",
      Hora: "02:00pm",
      RG: "151638366",
      Nome: "Eduardo Pinheiro",
      Empresa: "Instituto CTS",
      Setor: "Departamento de P&D",
      visitado: "Alessandra Rocha",
      Refeição: "Sim",
      Pagamento: "Por conta própria",
      idShedule: "399651231231 ",
    },
    {
      id: "4",
      data: "20/10/2022",
      Hora: "02:00pm",
      RG: "151638366",
      Nome: "Eduardo Pinheiro",
      Empresa: "Instituto CTS",
      Setor: "Departamento de P&D",
      visitado: "Alessandra Rocha",
      Refeição: "Sim",
      Pagamento: "Por conta própria",
      idShedule: "399651231231 ",
    },
    {
      id: "5",
      data: "20/10/2022",
      Hora: "02:00pm",
      RG: "151638366",
      Nome: "Eduardo Pinheiro",
      Empresa: "Instituto CTS",
      Setor: "Departamento de P&D",
      visitado: "Alessandra Rocha",
      Refeição: "Sim",
      Pagamento: "Por conta própria",
      idShedule: "399651231231",
    },
    {
      id: "5",
      data: "20/10/2022",
      Hora: "02:00pm",
      RG: "151638366",
      Nome: "Eduardo Pinheiro",
      Empresa: "Instituto CTS",
      Setor: "Departamento de P&D",
      visitado: "Alessandra Rocha",
      Refeição: "Sim",
      Pagamento: "Por conta própria",
      idShedule: "399651231231",
    },
    {
      id: "5",
      data: "20/10/2022",
      Hora: "02:00pm",
      RG: "151638366",
      Nome: "Eduardo Pinheiro",
      Empresa: "Instituto CTS",
      Setor: "Departamento de P&D",
      visitado: "Alessandra Rocha",
      Refeição: "Sim",
      Pagamento: "Por conta própria",
      idShedule: "399651231231",
    },
    {
      id: "5",
      data: "20/10/2022",
      Hora: "02:00pm",
      RG: "151638366",
      Nome: "Eduardo Pinheiro",
      Empresa: "Instituto CTS",
      Setor: "Departamento de P&D",
      visitado: "Alessandra Rocha",
      Refeição: "Sim",
      Pagamento: "Por conta própria",
      idShedule: "399651231231",
    },
    {
      id: "5",
      data: "20/10/2022",
      Hora: "02:00pm",
      RG: "151638366",
      Nome: "Eduardo Pinheiro",
      Empresa: "Instituto CTS",
      Setor: "Departamento de P&D",
      visitado: "Alessandra Rocha",
      Refeição: "Sim",
      Pagamento: "Por conta própria",
      idShedule: "399651231231",
    },
    {
      id: "5",
      data: "20/10/2022",
      Hora: "02:00pm",
      RG: "151638366",
      Nome: "Eduardo Pinheiro",
      Empresa: "Instituto CTS",
      Setor: "Departamento de P&D",
      visitado: "Alessandra Rocha",
      Refeição: "Sim",
      Pagamento: "Por conta própria",
      idShedule: "399651231231",
    },
    {
      id: "5",
      data: "20/10/2022",
      Hora: "02:00pm",
      RG: "151638366",
      Nome: "Eduardo Pinheiro",
      Empresa: "Instituto CTS",
      Setor: "Departamento de P&D",
      visitado: "Alessandra Rocha",
      Refeição: "Sim",
      Pagamento: "Por conta própria",
      idShedule: "399651231231",
    },
    {
      id: "5",
      data: "20/10/2022",
      Hora: "02:00pm",
      RG: "151638366",
      Nome: "Eduardo Pinheiro",
      Empresa: "Instituto CTS",
      Setor: "Departamento de P&D",
      visitado: "Alessandra Rocha",
      Refeição: "Sim",
      Pagamento: "Por conta própria",
      idShedule: "399651231231",
    },
    {
      id: "5",
      data: "20/10/2022",
      Hora: "02:00pm",
      RG: "151638366",
      Nome: "Eduardo Pinheiro",
      Empresa: "Instituto CTS",
      Setor: "Departamento de P&D",
      visitado: "Alessandra Rocha",
      Refeição: "Sim",
      Pagamento: "Por conta própria",
      idShedule: "399651231231",
    },
    {
      id: "5",
      data: "20/10/2022",
      Hora: "02:00pm",
      RG: "151638366",
      Nome: "Eduardo Pinheiro",
      Empresa: "Instituto CTS",
      Setor: "Departamento de P&D",
      visitado: "Alessandra Rocha",
      Refeição: "Sim",
      Pagamento: "Por conta própria",
      idShedule: "399651231231",
    },
    {
      id: "5",
      data: "20/10/2022",
      Hora: "02:00pm",
      RG: "151638366",
      Nome: "Eduardo Pinheiro",
      Empresa: "Instituto CTS",
      Setor: "Departamento de P&D",
      visitado: "Alessandra Rocha",
      Refeição: "Sim",
      Pagamento: "Por conta própria",
      idShedule: "399651231231",
    },
    {
      id: "5",
      data: "20/10/2022",
      Hora: "02:00pm",
      RG: "151638366",
      Nome: "Eduardo Pinheiro",
      Empresa: "Instituto CTS",
      Setor: "Departamento de P&D",
      visitado: "Alessandra Rocha",
      Refeição: "Sim",
      Pagamento: "Por conta própria",
      idShedule: "399651231231",
    },
    {
      id: "5",
      data: "20/10/2022",
      Hora: "02:00pm",
      RG: "151638366",
      Nome: "Eduardo Pinheiro",
      Empresa: "Instituto CTS",
      Setor: "Departamento de P&D",
      visitado: "Alessandra Rocha",
      Refeição: "Sim",
      Pagamento: "Por conta própria",
      idShedule: "399651231231",
    },
    {
      id: "5",
      data: "20/10/2022",
      Hora: "02:00pm",
      RG: "151638366",
      Nome: "Eduardo Pinheiro",
      Empresa: "Instituto CTS",
      Setor: "Departamento de P&D",
      visitado: "Alessandra Rocha",
      Refeição: "Sim",
      Pagamento: "Por conta própria",
      idShedule: "399651231231",
    },
    {
      id: "5",
      data: "20/10/2022",
      Hora: "02:00pm",
      RG: "151638366",
      Nome: "Eduardo Pinheiro",
      Empresa: "Instituto CTS",
      Setor: "Departamento de P&D",
      visitado: "Alessandra Rocha",
      Refeição: "Sim",
      Pagamento: "Por conta própria",
      idShedule: "399651231231",
    },
    {
      id: "5",
      data: "20/10/2022",
      Hora: "02:00pm",
      RG: "151638366",
      Nome: "Eduardo Pinheiro",
      Empresa: "Instituto CTS",
      Setor: "Departamento de P&D",
      visitado: "Alessandra Rocha",
      Refeição: "Sim",
      Pagamento: "Por conta própria",
      idShedule: "399651231231",
    },
    {
      id: "5",
      data: "20/10/2022",
      Hora: "02:00pm",
      RG: "151638366",
      Nome: "Eduardo Pinheiro",
      Empresa: "Instituto CTS",
      Setor: "Departamento de P&D",
      visitado: "Alessandra Rocha",
      Refeição: "Sim",
      Pagamento: "Por conta própria",
      idShedule: "399651231231",
    },
    {
      id: "5",
      data: "20/10/2022",
      Hora: "02:00pm",
      RG: "151638366",
      Nome: "Eduardo Pinheiro",
      Empresa: "Instituto CTS",
      Setor: "Departamento de P&D",
      visitado: "Alessandra Rocha",
      Refeição: "Sim",
      Pagamento: "Por conta própria",
      idShedule: "399651231231",
    },
    {
      id: "5",
      data: "20/10/2022",
      Hora: "02:00pm",
      RG: "151638366",
      Nome: "Eduardo Pinheiro",
      Empresa: "Instituto CTS",
      Setor: "Departamento de P&D",
      visitado: "Alessandra Rocha",
      Refeição: "Sim",
      Pagamento: "Por conta própria",
      idShedule: "399651231231",
    },
    {
      id: "5",
      data: "20/10/2022",
      Hora: "02:00pm",
      RG: "151638366",
      Nome: "Eduardo Pinheiro",
      Empresa: "Instituto CTS",
      Setor: "Departamento de P&D",
      visitado: "Alessandra Rocha",
      Refeição: "Sim",
      Pagamento: "Por conta própria",
      idShedule: "399651231231",
    },
    {
      id: "5",
      data: "20/10/2022",
      Hora: "02:00pm",
      RG: "151638366",
      Nome: "Eduardo Pinheiro",
      Empresa: "Instituto CTS",
      Setor: "Departamento de P&D",
      visitado: "Alessandra Rocha",
      Refeição: "Sim",
      Pagamento: "Por conta própria",
      idShedule: "399651231231",
    },
    {
      id: "5",
      data: "20/10/2022",
      Hora: "02:00pm",
      RG: "151638366",
      Nome: "Eduardo Pinheiro",
      Empresa: "Instituto CTS",
      Setor: "Departamento de P&D",
      visitado: "Alessandra Rocha",
      Refeição: "Sim",
      Pagamento: "Por conta própria",
      idShedule: "399651231231",
    },
    {
      id: "5",
      data: "20/10/2022",
      Hora: "02:00pm",
      RG: "151638366",
      Nome: "Eduardo Pinheiro",
      Empresa: "Instituto CTS",
      Setor: "Departamento de P&D",
      visitado: "Alessandra Rocha",
      Refeição: "Sim",
      Pagamento: "Por conta própria",
      idShedule: "399651231231",
    },
  ];

  useEffect(() => {
    setRows(responseData);
  }, []);

  return (
    <>
      <CreateModal />
      <ToolbarContainer
        title="Agendamentos"
        captionButton="Criar Agendamento"
      />
      <TableGrid rows={rows} columns={columns} />
    </>
  );
}
